name: User App CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "apps/user/**"
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/user-ci-cd.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "prod"

# 워크플로우에 필요한 권한 추가
permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  build:
    name: 빌드 검사
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/user
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install
        working-directory: ./ # 루트에서 실행

      - name: Build Next.js app
        run: pnpm --filter o2o-user build